### PR TITLE
requirements.txt update for lra

### PR DESCRIPTION
**Pull request by radarFudan**

### CODE REVIEW

**Comment by radarFudan** [comment]
I tried to run the code and found the code for Long Range Arena will require several additional torch-related packages.

**Comment by albertfgu** [comment]
Thanks for the contribution, thanks for pointing this out! I'll hold off on merging this specific PR because there is a planned v4 release that incorporates these changes. The scikit-learn dependency was already added: https://github.com/HazyResearch/state-spaces/blob/v4/requirements.txt

The `torchaudio` and `torchvision` dependencies were left off on purpose (as is `pytorch` itself) because they are usually installed together with PyTorch when using conda. Would it be helpful to add a note to the README?

**Comment by radarFudan** [comment]
Thank you so much! I'm perfectly ok with your release plan~

**Comment by albertfgu** [comment]
The v4.0 release updated the requirements.txt file and README and hopefully addresses this!

**Pull request closed without merging**
